In [3]:
import numpy as np

In [4]:
a = np.array([[1,2,3], 
              [3,2,1]])

In [5]:
a.ndim

2

In [6]:
a.shape

(2, 3)

In [7]:
a.size

6

In [8]:
a.dtype

dtype('int64')

In [9]:
np.zeros((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [10]:
np.ones_like(a)

array([[1, 1, 1],
       [1, 1, 1]])

In [11]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [14]:
np.random.randint(1,10,(3,4))

array([[5, 6, 2, 1],
       [3, 5, 2, 4],
       [2, 3, 9, 2]])

In [22]:
np.random.seed(1)
np.random.randint(1,10,(3,4))

array([[6, 9, 6, 1],
       [1, 2, 8, 7],
       [3, 5, 6, 3]])

In [23]:
np.repeat(10,5)

array([10, 10, 10, 10, 10])

In [24]:
onedim_array= np.array([1,2,3,4,5])
multidim_array= np.repeat(onedim_array, 3)
multidim_array

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5])

In [26]:
multidim_array= np.tile(onedim_array, (5,2))
multidim_array

array([[1, 2, 3, 4, 5, 1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5, 1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5, 1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5, 1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]])

In [28]:
b= np.array([[5,4,3,2,1,0], [10,8,6,4,2,0]])
b.T

array([[ 5, 10],
       [ 4,  8],
       [ 3,  6],
       [ 2,  4],
       [ 1,  2],
       [ 0,  0]])

In [29]:
b

array([[ 5,  4,  3,  2,  1,  0],
       [10,  8,  6,  4,  2,  0]])

In [30]:
b.reshape(4,3)

array([[ 5,  4,  3],
       [ 2,  1,  0],
       [10,  8,  6],
       [ 4,  2,  0]])

In [32]:
b.flatten()

array([ 5,  4,  3,  2,  1,  0, 10,  8,  6,  4,  2,  0])

In [33]:
a

array([[1, 2, 3],
       [3, 2, 1]])

In [34]:
b

array([[ 5,  4,  3,  2,  1,  0],
       [10,  8,  6,  4,  2,  0]])

In [35]:
np.hstack((b,a))

array([[ 5,  4,  3,  2,  1,  0,  1,  2,  3],
       [10,  8,  6,  4,  2,  0,  3,  2,  1]])

In [36]:
np.vstack((b.reshape(4,3), a))

array([[ 5,  4,  3],
       [ 2,  1,  0],
       [10,  8,  6],
       [ 4,  2,  0],
       [ 1,  2,  3],
       [ 3,  2,  1]])

In [37]:
arr1 = np.array([5,10,15,20])
arr1

array([ 5, 10, 15, 20])

In [39]:
arr2 = np.arange(5,9)
arr2

array([5, 6, 7, 8])

In [40]:
arr1-arr2

array([ 0,  4,  8, 12])

In [41]:
arr1*2

array([10, 20, 30, 40])

In [42]:
arr1

array([ 5, 10, 15, 20])

In [43]:
arr1.mean()

12.5

In [ ]:
np.median(arr1) #this is a function not method if you execute arr1.median() you will get error

12.5

In [46]:
tens = np.arange(0,120, 10)
tens

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110])

In [47]:
tens = np.arange(0,120, 10).reshape(3,4)
tens

array([[  0,  10,  20,  30],
       [ 40,  50,  60,  70],
       [ 80,  90, 100, 110]])

In [48]:
horizontal = np.array([-5,-10,-15,-20])
horizontal

array([ -5, -10, -15, -20])

In [49]:
tens+horizontal

array([[-5,  0,  5, 10],
       [35, 40, 45, 50],
       [75, 80, 85, 90]])

In [50]:
tens

array([[  0,  10,  20,  30],
       [ 40,  50,  60,  70],
       [ 80,  90, 100, 110]])

In [ ]:
tens.mean(axis=0) #column wise operation

array([40., 50., 60., 70.])

In [52]:
(0+40+80)/3

40.0

In [53]:
tens.mean(axis=1) #rows

array([15., 55., 95.])